title: dsst
email: massimo.nocentini@gmail.com
description: > # this means to ignore newlines until "baseurl:". This description will appear in your document head meta (for Google search results) and in your feed.xml site description.
  You must never think of the whole street at once, understand? You must only
  concentrate on the next step, the next breath, the next stroke of the broom, and the
  next, and the next. Nothing else.
  —Beppo Roadsweeper, in Momo by Michael Ende
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://massimo-nocentini.github.io/dsst" # the base hostname & protocol for your site
github_username:  massimo-nocentini

# Build settings
markdown: kramdown

exclude: [Makefile]

theme: jekyll-theme-minimal
